---
apiVersion: v1
kind: Pod
metadata:
  name: player-pod
  labels:
    app: f1-player
    test: test2
spec:
  restartPolicy: OnFailure
  volumes:
    - name: data-pv-storage
      persistentVolumeClaim:
        claimName: data-pv-claim
  containers:
    - name: f1-player
      image: mgunter/python-f1-play
      args: ["test1.sqlite3"]
      ports:
        - containerPort: 20777
          protocol: UDP
          name: "udp-server"
      volumeMounts:
        - mountPath: "/sensable"
          name: data-pv-storage