apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    nodePort: 32181
  - name: follower
    port: 2888
    protocol: TCP
    nodePort: 32182
  - name: leader
    port: 3888
    protocol: TCP
    nodePort: 32183
  selector:
    app: zookeeper-1
  type: NodePort